// Code generated by internal/cmd/protocolgen; DO NOT EDIT.
package protocol

const (
	Version                     = 1
	HeaderSize                  = 12
	MaxPayloadSize              = 8388608
	AddressFamilyIPv4    byte   = 4
	AddressFamilyIPv6    byte   = 6
	AddressHeaderSize           = 8
	AddressIPv4Size             = 12
	AddressIPv6Size             = 24
	DatagramMetadataSize        = 48
	DatagramDestination  uint32 = 1
	DatagramInterface    uint32 = 2
	DatagramHopLimit     uint32 = 4
	DatagramTrafficClass uint32 = 8
	DatagramTimestamp    uint32 = 16
)

var magic = [4]byte{'M', 'O', 'G', 'A'}

const (
	OpTCPConnect         Operation = 1
	OpDNSLookup          Operation = 2
	OpUDPConnect         Operation = 3
	OpUDPSend            Operation = 4
	OpUDPReceive         Operation = 5
	OpUDPOpen            Operation = 6
	OpUDPSendTo          Operation = 7
	OpUDPReceiveFrom     Operation = 8
	OpUDPOpenMetadata    Operation = 9
	OpFileOpen           Operation = 10
	OpFileRead           Operation = 11
	OpFileWrite          Operation = 12
	OpFileSeek           Operation = 13
	OpFileStat           Operation = 14
	OpFileClose          Operation = 15
	OpUDPConnectMetadata Operation = 16
	OpUDPSendMsg         Operation = 17
	OpUDPReceiveMsg      Operation = 18
)
