package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

type schema struct {
	Magic          string      `json:"magic"`
	Version        int         `json:"version"`
	HeaderSize     int         `json:"header_size"`
	MaxPayloadSize int         `json:"max_payload_size"`
	Operations     []operation `json:"operations"`
	Address        address     `json:"address"`
	Datagram       datagram    `json:"datagram_metadata"`
}

type operation struct {
	Go    string `json:"go"`
	C     string `json:"c"`
	Value int    `json:"value"`
}

type address struct {
	FamilyIPv4 int `json:"family_ipv4"`
	FamilyIPv6 int `json:"family_ipv6"`
	HeaderSize int `json:"header_size"`
	IPv4Size   int `json:"ipv4_size"`
	IPv6Size   int `json:"ipv6_size"`
}

type datagram struct {
	Size         int `json:"size"`
	Destination  int `json:"destination"`
	Interface    int `json:"interface"`
	HopLimit     int `json:"hop_limit"`
	TrafficClass int `json:"traffic_class"`
	Timestamp    int `json:"timestamp"`
}

func main() {
	check := flag.Bool("check", false, "fail if generated files are stale")
	flag.Parse()
	root, err := findRoot()
	if err != nil {
		fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, "protocol", "schema.json"))
	if err != nil {
		fatal(err)
	}
	var contract schema
	if err := json.Unmarshal(data, &contract); err != nil {
		fatal(fmt.Errorf("decode schema: %w", err))
	}
	if err := contract.validate(); err != nil {
		fatal(err)
	}
	goOutput, err := generateGo(contract)
	if err != nil {
		fatal(err)
	}
	outputs := map[string][]byte{
		filepath.Join(root, "internal", "protocol", "generated.go"): goOutput,
		filepath.Join(root, "injector", "protocol_generated.h"):     generateC(contract),
	}
	for path, output := range outputs {
		if *check {
			current, readErr := os.ReadFile(path)
			if readErr != nil || !bytes.Equal(current, output) {
				fatal(fmt.Errorf("generated file is stale: %s", path))
			}
			continue
		}
		if err := os.WriteFile(path, output, 0o644); err != nil {
			fatal(err)
		}
	}
}

func (s schema) validate() error {
	if len(s.Magic) != 4 || s.Version <= 0 || s.Version > 255 || s.HeaderSize != 12 || s.MaxPayloadSize <= 0 {
		return errors.New("invalid wire contract header")
	}
	seen := make(map[int]bool)
	for _, op := range s.Operations {
		if op.Go == "" || op.C == "" || op.Value <= 0 || op.Value > 255 || seen[op.Value] {
			return fmt.Errorf("invalid operation %+v", op)
		}
		seen[op.Value] = true
	}
	if s.Address.FamilyIPv4 <= 0 || s.Address.FamilyIPv6 <= 0 || s.Address.IPv4Size != 12 || s.Address.IPv6Size != 24 {
		return errors.New("invalid canonical address contract")
	}
	if s.Datagram.Size != 48 || s.Datagram.Destination == 0 || s.Datagram.Interface == 0 ||
		s.Datagram.HopLimit == 0 || s.Datagram.TrafficClass == 0 || s.Datagram.Timestamp == 0 {
		return errors.New("invalid datagram metadata contract")
	}
	return nil
}

func generateGo(s schema) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by internal/cmd/protocolgen; DO NOT EDIT.")
	fmt.Fprintln(&out, "package protocol")
	fmt.Fprintln(&out, "\nconst (")
	fmt.Fprintf(&out, "\tVersion = %d\n\tHeaderSize = %d\n\tMaxPayloadSize = %d\n", s.Version, s.HeaderSize, s.MaxPayloadSize)
	fmt.Fprintf(&out, "\tAddressFamilyIPv4 byte = %d\n\tAddressFamilyIPv6 byte = %d\n", s.Address.FamilyIPv4, s.Address.FamilyIPv6)
	fmt.Fprintf(&out, "\tAddressHeaderSize = %d\n\tAddressIPv4Size = %d\n\tAddressIPv6Size = %d\n", s.Address.HeaderSize, s.Address.IPv4Size, s.Address.IPv6Size)
	fmt.Fprintf(&out, "\tDatagramMetadataSize = %d\n", s.Datagram.Size)
	fmt.Fprintf(&out, "\tDatagramDestination uint32 = %d\n\tDatagramInterface uint32 = %d\n", s.Datagram.Destination, s.Datagram.Interface)
	fmt.Fprintf(&out, "\tDatagramHopLimit uint32 = %d\n\tDatagramTrafficClass uint32 = %d\n\tDatagramTimestamp uint32 = %d\n", s.Datagram.HopLimit, s.Datagram.TrafficClass, s.Datagram.Timestamp)
	fmt.Fprintln(&out, ")")
	fmt.Fprintf(&out, "\nvar magic = [4]byte{%q, %q, %q, %q}\n", s.Magic[0], s.Magic[1], s.Magic[2], s.Magic[3])
	fmt.Fprintln(&out, "\nconst (")
	for _, op := range s.Operations {
		fmt.Fprintf(&out, "\t%s Operation = %d\n", op.Go, op.Value)
	}
	fmt.Fprintln(&out, ")")
	return format.Source(out.Bytes())
}

func generateC(s schema) []byte {
	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by internal/cmd/protocolgen; DO NOT EDIT. */")
	fmt.Fprintln(&out, "#ifndef MOGATE_PROTOCOL_GENERATED_H\n#define MOGATE_PROTOCOL_GENERATED_H")
	fmt.Fprintf(&out, "#define MG_PROTOCOL_VERSION %d\n#define MG_HEADER_SIZE %d\n#define MG_MAX_PAYLOAD %dU\n", s.Version, s.HeaderSize, s.MaxPayloadSize)
	fmt.Fprintf(&out, "#define MG_ADDRESS_FAMILY_IPV4 %d\n#define MG_ADDRESS_FAMILY_IPV6 %d\n", s.Address.FamilyIPv4, s.Address.FamilyIPv6)
	fmt.Fprintf(&out, "#define MG_ADDRESS_HEADER_SIZE %d\n#define MG_ADDRESS_IPV4_SIZE %d\n#define MG_ADDRESS_IPV6_SIZE %d\n", s.Address.HeaderSize, s.Address.IPv4Size, s.Address.IPv6Size)
	fmt.Fprintf(&out, "#define MG_DATAGRAM_METADATA_SIZE %d\n", s.Datagram.Size)
	fmt.Fprintf(&out, "#define MG_DATAGRAM_DESTINATION %dU\n#define MG_DATAGRAM_INTERFACE %dU\n", s.Datagram.Destination, s.Datagram.Interface)
	fmt.Fprintf(&out, "#define MG_DATAGRAM_HOP_LIMIT %dU\n#define MG_DATAGRAM_TRAFFIC_CLASS %dU\n#define MG_DATAGRAM_TIMESTAMP %dU\n", s.Datagram.HopLimit, s.Datagram.TrafficClass, s.Datagram.Timestamp)
	operations := append([]operation(nil), s.Operations...)
	sort.Slice(operations, func(i, j int) bool { return operations[i].Value < operations[j].Value })
	for _, op := range operations {
		fmt.Fprintf(&out, "#define %s %d\n", op.C, op.Value)
	}
	fmt.Fprintln(&out, "#endif")
	return out.Bytes()
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "protocol", "schema.json")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("repository root not found")
		}
		dir = parent
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
